# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.cache/wt [current_project]
set_property parent.project_path E:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo e:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  E:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/sources_1/new/FSMD_microphone.vhd
  E:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/sources_1/new/audio_interface.vhd
  E:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/sources_1/new/en_4_cycles.vhd
  E:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/sources_1/new/pwm.vhd
  E:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/sources_1/new/controlador.vhd
}
read_ip -quiet E:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12MHz/clk_12MHz.xci
set_property used_in_implementation false [get_files -all e:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12MHz/clk_12MHz_board.xdc]
set_property used_in_implementation false [get_files -all e:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12MHz/clk_12MHz.xdc]
set_property used_in_implementation false [get_files -all e:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12MHz/clk_12MHz_ooc.xdc]
set_property is_locked true [get_files E:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12MHz/clk_12MHz.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/constrs_1/imports/DSED_Grupo6/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files E:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/constrs_1/imports/DSED_Grupo6/Nexys4DDR_Master.xdc]


synth_design -top controlador -part xc7a100tcsg324-1


write_checkpoint -force -noxdef controlador.dcp

catch { report_utilization -file controlador_utilization_synth.rpt -pb controlador_utilization_synth.pb }
