# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/fpga/Downloads/dsed_audio-20171221T102638Z-001/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12MHz/clk_12MHz.xci
# IP: The module: 'clk_12MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fpga/Downloads/dsed_audio-20171221T102638Z-001/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12MHz/clk_12MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/fpga/Downloads/dsed_audio-20171221T102638Z-001/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12MHz/clk_12MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/fpga/Downloads/dsed_audio-20171221T102638Z-001/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12MHz/clk_12MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/fpga/Downloads/dsed_audio-20171221T102638Z-001/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12MHz/clk_12MHz.xci
# IP: The module: 'clk_12MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fpga/Downloads/dsed_audio-20171221T102638Z-001/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12MHz/clk_12MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/fpga/Downloads/dsed_audio-20171221T102638Z-001/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12MHz/clk_12MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/fpga/Downloads/dsed_audio-20171221T102638Z-001/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12MHz/clk_12MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
