# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/sources_1/ip/RAM/RAM.xci
# IP: The module: 'RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/sources_1/ip/RAM/RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/sources_1/ip/RAM/RAM.xci
# IP: The module: 'RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/DSED_Grupo6/Proyecto/dsed_audio/dsed_audio.srcs/sources_1/ip/RAM/RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
